# Generated by Django 3.1.3 on 2020-11-13 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20201113_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Guest',
        ),
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='room',
        ),
        migrations.RemoveField(
            model_name='category',
            name='to_date',
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, max_length=300, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_review', to='property.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('Guest', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_book', to='property.room')),
            ],
        ),
    ]
