# Generated by Django 3.1.3 on 2020-11-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201113_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_category', to='property.category'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image2',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image3',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image4',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image5',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
    ]
