# Generated by Django 3.1.3 on 2020-11-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20201115_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='image5',
        ),
    ]
