# Generated by Django 3.1.3 on 2020-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20201116_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='plase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_image/'),
        ),
    ]
