# Generated by Django 3.1.3 on 2020-11-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20201116_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='plase',
        ),
    ]
